
using SpeechlyTouch.DataService.Interfaces;
using SpeechlyTouch.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Windows.UI.Xaml.Media.Imaging;

namespace SpeechlyTouch.Services.Languages
{
    public class LanguagesService : ILanguagesService
    {
        private readonly IDataService _dataService;
        List<Language> languages;
        List<Language> approvedlanguages;

        public LanguagesService(IDataService dataService)
        {
            _dataService = dataService;
        }
        public async Task<List<Language>> GetSupportedLanguagesAsync()
        {
            if (approvedlanguages != null && approvedlanguages.Any()) return approvedlanguages;

            languages = new List<Language>
                {
                    // The first five are quick view languages
                    new Language() { DisplayName = "Français", DisplayCode = "FR", CountryCode = "FR", CountryName = "France", CountryNativeName = "France",  Name = "Français (France)", EnglishName = "French", Code = "fr-FR", Voice = "fr-FR-Julie-Apollo", Flag = FlagImageSource("fr.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "SPA",CountryCode = "ES", CountryName = "Spain", CountryNativeName = "España", Name = "Español (Spain)", EnglishName = "Spanish", Code = "es-ES", Voice = "es-ES-Laura-Apollo", Flag = FlagImageSource("es.svg") },
                    new Language() { DisplayName = "Italiano", DisplayCode = "ITA",CountryCode = "IT", CountryName = "Italy", CountryNativeName = "Italia", Name = "Italiano (Italy)", EnglishName = "Italian", Code = "it-IT", Voice = "it-IT-Cosimo-Apollo", Flag = FlagImageSource("it.svg") },
                    new Language() { DisplayName = "Nederlands", DisplayCode = "NET",CountryCode = "NL", CountryName = "Netherlands", CountryNativeName = "Nederland", Name = "Nederlands (Netherlands)", EnglishName = "Dutch", Code = "nl-NL", Voice = "nl-NL-HannaRUS", Flag = FlagImageSource("nl.svg") },
                    new Language() { DisplayName = "Svenska", DisplayCode = "SWE",CountryCode = "SE", CountryName = "Sweden", CountryNativeName = "Sverige", Name = "Svenska (Sweden)", EnglishName = "Swedish", Code = "sv-SE", Voice = "sv-SE-HedvigRUS", Flag = FlagImageSource("se.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "SA",CountryCode = "SA", CountryName = "Saudi Arabia", CountryNativeName = "المملكة العربية السعودية", Name = "العربية (Saudi Arabia)", EnglishName = "Arabic", Code = "ar-SA", Voice = "ar-SA-Naayf", Flag = FlagImageSource("sa.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "AE",CountryCode = "AE", CountryName = "United Arab Emirates", CountryNativeName = "اَلْإِمَارَات الْعَرَبِيَة الْمُتَحِدَة", Name = "الِْإمَارَات (United Arab Emirates)", EnglishName = "Arabic", Code = "ar-AE", Voice = "ar-AE-FatimaNeural", Flag = FlagImageSource("ae.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "DZ",CountryCode = "DZ", CountryName = "Algeria", CountryNativeName = "الجزائر", Name = "الجزائر (Algeria)", EnglishName = "Arabic", Code = "ar-DZ", Voice = "ar-DZ-AminaNeural", Flag = FlagImageSource("dz.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "BH",CountryCode = "BH", CountryName = "Bahrain", CountryNativeName = "البحرين", Name = "البحرين (Bahrain)", EnglishName = "Arabic", Code = "ar-BH", Voice = "ar-BH-AliNeural", Flag = FlagImageSource("bh.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "EG",CountryCode = "EG", CountryName = "Egypt", CountryNativeName = "مصر", Name = "مصر (Egypt)", EnglishName = "Arabic", Code = "ar-EG", Voice = "ar-EG-SalmaNeural", Flag = FlagImageSource("eg.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "IQ",CountryCode = "IQ", CountryName = "Iraq", CountryNativeName = "العراق", Name = "العراق (Iraq)", EnglishName = "Arabic", Code = "ar-IQ", Voice = "ar-IQ-BasselNeural", Flag = FlagImageSource("iq.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "JO",CountryCode = "JO", CountryName = "Jordan", CountryNativeName = "الأردن", Name = "الأردن (Jordan)", EnglishName = "Arabic", Code = "ar-JO", Voice = "ar-JO-SanaNeural", Flag = FlagImageSource("jo.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "KW",CountryCode = "KW", CountryName = "Kuwait", CountryNativeName = "الكويت", Name = "الكويت (Kuwait)", EnglishName = "Arabic", Code = "ar-KW", Voice = "ar-KW-FahedNeural", Flag = FlagImageSource("kw.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "LB",CountryCode = "LB", CountryName = "Lebanon", CountryNativeName = "لبنان", Name = "لبنان (Lebanon)", EnglishName = "Arabic", Code = "ar-LB", Voice = "ar-LB-LaylaNeural", Flag = FlagImageSource("lb.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "LY",CountryCode = "LY", CountryName = "Libya", CountryNativeName = "ليبيا", Name = "ليبيا (Libya)", EnglishName = "Arabic", Code = "ar-LY", Voice = "ar-LY-ImanNeural", Flag = FlagImageSource("ly.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "MA",CountryCode = "MA", CountryName = "Morocco", CountryNativeName = "المغرب", Name = "المغرب (Morocco)", EnglishName = "Arabic", Code = "ar-MA", Voice = "ar-MA-JamalNeural", Flag = FlagImageSource("ma.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "OM",CountryCode = "OM", CountryName = "Oman", CountryNativeName = "سلطنة عمان", Name = "سلطنة عمان (Oman)", EnglishName = "Arabic", Code = "ar-OM", Voice = "ar-OM-AbdullahNeural", Flag = FlagImageSource("om.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "QA",CountryCode = "QA", CountryName = "Qatar", CountryNativeName = "دولة قطر", Name = "دولة قطر (Qatar)", EnglishName = "Arabic", Code = "ar-QA", Voice = "ar-QA-AmalNeural", Flag = FlagImageSource("qa.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "SY",CountryCode = "SY", CountryName = "Syria", CountryNativeName = "سوريا", Name = "سوريا (Syria)", EnglishName = "Arabic", Code = "ar-SY", Voice = "ar-SY-AmanyNeural", Flag = FlagImageSource("sy.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "TN",CountryCode = "TN", CountryName = "Tunisia", CountryNativeName = "تونس", Name = "تونس (Tunisia)", EnglishName = "Arabic", Code = "ar-TN", Voice = "ar-TN-HediNeural", Flag = FlagImageSource("tn.svg") },
                    new Language() { DisplayName = "العربية", DisplayCode = "YE",CountryCode = "YE", CountryName = "Yemen", CountryNativeName = "اليمن", Name = "اليمن (Yemen)", EnglishName = "Arabic", Code = "ar-YE", Voice = "ar-YE-MaryamNeural", Flag = FlagImageSource("ye.svg") },
                    new Language() { DisplayName = "Deutsch", DisplayCode = "GER",CountryCode = "DE", CountryName = "Germany", CountryNativeName = "Deutschland", Name = "Deutsch (Germany)", EnglishName = "German", Code = "de-DE", Voice = "de-DE-Hedda", Flag = FlagImageSource("de.svg") },
                    new Language() { DisplayName = "Deutsch", DisplayCode = "AT",CountryCode = "AT", CountryName = "Austria", CountryNativeName = "Österreich", Name = "Österreich (Austria)", EnglishName = "German", Code = "de-AT", Voice = "de-AT-IngridNeural", Flag = FlagImageSource("at.svg") },
                    new Language() { DisplayName = "Deutsch", DisplayCode = "CH",CountryCode = "CH", CountryName = "Switzerland", CountryNativeName = "Schweiz", Name = "Schweiz (Switzerland)", EnglishName = "German", Code = "de-CH", Voice = "de-CH-JanNeural", Flag = FlagImageSource("ch.svg") },
                    new Language() { DisplayName = "English", DisplayCode = "CAN",CountryCode = "CA", CountryName = "Canada", CountryNativeName = "Canada", Name = "English (Canada)", EnglishName = "English", Code = "en-CA", Voice = "en-CA-Linda", Flag = FlagImageSource("ca.svg") },
                    new Language() { DisplayName = "English", DisplayCode = "UK",CountryCode = "GB", CountryName = "United Kingdom", CountryNativeName = "United Kingdom", Name = "English (United Kingdom)", EnglishName = "English", Code = "en-GB", Voice = "en-GB-Susan-Apollo", Flag = FlagImageSource("gb.svg") },
                    new Language() { DisplayName = "English", DisplayCode = "IND",CountryCode = "IN", CountryName = "India", CountryNativeName = "India", Name = "English (India)", EnglishName = "English", Code = "en-IN", Voice = "en-IN-Heera-Apollo", Flag = FlagImageSource("in.svg") },
                    new Language() { DisplayName = "English", DisplayCode = "US",CountryCode = "US", CountryName = "United States", CountryNativeName = "United States", Name = "English (United States)", EnglishName = "English", Code = "en-US", Voice = "en-US-ZiraRUS", Flag = FlagImageSource("us.svg")},
                    new Language() { DisplayName = "English", DisplayCode = "HK",CountryCode = "HK", CountryName = "Hong Kong", CountryNativeName = "Hong Kong", Name = "English (Hong Kong)", EnglishName = "English", Code = "en-HK", Voice = "en-HK-SamNeural", Flag = FlagImageSource("hk.svg")},
                    new Language() { DisplayName = "English", DisplayCode = "IE",CountryCode = "IE", CountryName = "Ireland", CountryNativeName = "Ireland", Name = "English (Ireland)", EnglishName = "English", Code = "en-IE", Voice = "en-IE-ConnorNeural", Flag = FlagImageSource("ie.svg")},
                    new Language() { DisplayName = "English", DisplayCode = "KE",CountryCode = "KE", CountryName = "Kenya", CountryNativeName = "Kenya", Name = "English (Kenya)", EnglishName = "English", Code = "en-KE", Voice = "en-KE-AsiliaNeural", Flag = FlagImageSource("ke.svg")},
                    new Language() { DisplayName = "English", DisplayCode = "NG",CountryCode = "NG", CountryName = "Nigeria", CountryNativeName = "Nigeria", Name = "English (Nigeria)", EnglishName = "English", Code = "en-NG", Voice = "en-NG-AbeoNeural", Flag = FlagImageSource("ng.svg")},
                    new Language() { DisplayName = "English", DisplayCode = "NG",CountryCode = "NG", CountryName = "New Zealand", CountryNativeName = "New Zealand", Name = "English (New Zealand)", EnglishName = "English", Code = "en-NZ", Voice = "en-NZ-MitchellNeural", Flag = FlagImageSource("nz.svg")},
                    new Language() { DisplayName = "English", DisplayCode = "PH",CountryCode = "PH", CountryName = "Philippines", CountryNativeName = "Philippines", Name = "English (Philippines)", EnglishName = "English", Code = "en-PH", Voice = "en-PH-JamesNeural", Flag = FlagImageSource("ph.svg")},
                    new Language() { DisplayName = "English", DisplayCode = "SG",CountryCode = "SG", CountryName = "Singapore", CountryNativeName = "Singapore", Name = "English (Singapore)", EnglishName = "English", Code = "en-SG", Voice = "en-SG-LunaNeural", Flag = FlagImageSource("sg.svg")},
                    new Language() { DisplayName = "English", DisplayCode = "TZ",CountryCode = "TZ", CountryName = "Tanzania", CountryNativeName = "Tanzania", Name = "English (Tanzania)", EnglishName = "English", Code = "en-TZ", Voice = "en-TZ-ElimuNeural", Flag = FlagImageSource("tz.svg")},
                    new Language() { DisplayName = "English", DisplayCode = "ZA",CountryCode = "ZA", CountryName = "South Africa", CountryNativeName = "South Africa", Name = "English (South Africa)", EnglishName = "English", Code = "en-ZA", Voice = "en-ZA-LeahNeural", Flag = FlagImageSource("za.svg")},
                    new Language() { DisplayName = "Español", DisplayCode = "MX",CountryCode = "MX", CountryName = "Mexico", CountryNativeName = "México", Name = "Español (Mexico)", EnglishName = "Spanish", Code = "es-MX", Voice = "es-MX-HildaRUS", Flag = FlagImageSource("mx.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "AR",CountryCode = "AR", CountryName = "Argentina", CountryNativeName = "Argentina", Name = "Español (Argentina)", EnglishName = "Spanish", Code = "es-AR", Voice = "es-AR-ElenaNeural", Flag = FlagImageSource("ar.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "BO",CountryCode = "BO", CountryName = "Bolivia", CountryNativeName = "Bolivia", Name = "Español (Bolivia)", EnglishName = "Spanish", Code = "es-BO", Voice = "es-BO-MarceloNeural", Flag = FlagImageSource("bo.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "CL",CountryCode = "CL", CountryName = "Chile", CountryNativeName = "Chile", Name = "Español (Chile)", EnglishName = "Spanish", Code = "es-CL", Voice = "es-CL-CatalinaNeural", Flag = FlagImageSource("cl.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "CO",CountryCode = "CO", CountryName = "Colombia", CountryNativeName = "Colombia", Name = "Español (Colombia)", EnglishName = "Spanish", Code = "es-CO", Voice = "es-CO-GonzaloNeural", Flag = FlagImageSource("co.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "CR",CountryCode = "CR", CountryName = "Costa Rica", CountryNativeName = "Costa Rica", Name = "Español (Costa Rica)", EnglishName = "Spanish", Code = "es-CR", Voice = "es-CR-JuanNeural", Flag = FlagImageSource("cr.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "CU",CountryCode = "CU", CountryName = "Cuba", CountryNativeName = "Cuba", Name = "Español (Cuba)", EnglishName = "Spanish", Code = "es-CU", Voice = "es-CU-BelkysNeural", Flag = FlagImageSource("cu.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "DO",CountryCode = "DO", CountryName = "Dominican Republic", CountryNativeName = "República Dominicana", Name = "Español (Dominican Republic)", EnglishName = "Spanish", Code = "es-DO", Voice = "es-DO-EmilioNeural", Flag = FlagImageSource("do.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "EC",CountryCode = "EC", CountryName = "Ecuador", CountryNativeName = "Ecuador", Name = "Español (Ecuador)", EnglishName = "Spanish", Code = "es-EC", Voice = "es-EC-AndreaNeural", Flag = FlagImageSource("ec.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "GQ",CountryCode = "GQ", CountryName = "Equatorial Guinea", CountryNativeName = "Guinea Ecuatorial", Name = "Español (Equatorial Guinea)", EnglishName = "Spanish", Code = "es-GQ", Voice = "es-GQ-JavierNeural", Flag = FlagImageSource("gq.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "GT",CountryCode = "GT", CountryName = "Guatemala", CountryNativeName = "Guatemala", Name = "Español (Guatemala)", EnglishName = "Spanish", Code = "es-GT", Voice = "es-GT-AndresNeural", Flag = FlagImageSource("gt.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "HN",CountryCode = "HN", CountryName = "Honduras", CountryNativeName = "Honduras", Name = "Español (Honduras)", EnglishName = "Spanish", Code = "es-HN", Voice = "es-HN-CarlosNeural", Flag = FlagImageSource("hn.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "NI",CountryCode = "NI", CountryName = "Nicaragua", CountryNativeName = "Nicaragua", Name = "Español (Nicaragua)", EnglishName = "Spanish", Code = "es-NI", Voice = "es-NI-FedericoNeural", Flag = FlagImageSource("ni.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "PA",CountryCode = "PA", CountryName = "Panama", CountryNativeName = "Panamá", Name = "Español (Panama)", EnglishName = "Spanish", Code = "es-PA", Voice = "es-PA-MargaritaNeural", Flag = FlagImageSource("pa.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "PE",CountryCode = "PE", CountryName = "Peru", CountryNativeName = "Perú", Name = "Español (Peru)", EnglishName = "Spanish", Code = "es-PE", Voice = "es-PE-AlexNeural", Flag = FlagImageSource("pe.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "PR",CountryCode = "PR", CountryName = "Puerto Rico", CountryNativeName = "Puerto Rico", Name = "Español (Puerto Rico)", EnglishName = "Spanish", Code = "es-PR", Voice = "es-PR-KarinaNeural", Flag = FlagImageSource("pr.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "PY",CountryCode = "PY", CountryName = "Paraguay", CountryNativeName = "Paraguay", Name = "Español (Paraguay)", EnglishName = "Spanish", Code = "es-PY", Voice = "es-PY-MarioNeural", Flag = FlagImageSource("py.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "SV",CountryCode = "SV", CountryName = "El Salvador", CountryNativeName = "El Salvador", Name = "Español (El Salvador)", EnglishName = "Spanish", Code = "es-SV", Voice = "es-SV-LorenaNeural", Flag = FlagImageSource("sv.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "US",CountryCode = "US", CountryName = "United States", CountryNativeName = "Estados Unidos", Name = "Español (United States)", EnglishName = "Spanish", Code = "es-US", Voice = "es-US-AlonsoNeural", Flag = FlagImageSource("us.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "UY",CountryCode = "UY", CountryName = "Uruguay", CountryNativeName = "Uruguay", Name = "Español (Uruguay)", EnglishName = "Spanish", Code = "es-UY", Voice = "es-UY-MateoNeural", Flag = FlagImageSource("uy.svg") },
                    new Language() { DisplayName = "Español", DisplayCode = "VE",CountryCode = "VE", CountryName = "Venezuela", CountryNativeName = "Venezuela", Name = "Español (Venezuela)", EnglishName = "Spanish", Code = "es-VE", Voice = "es-VE-PaolaNeural", Flag = FlagImageSource("ve.svg") },
                    new Language() { DisplayName = "Français", DisplayCode = "CAN",CountryCode = "CA", CountryName = "Canada", CountryNativeName = "Canada", Name = "Français (Canada)", EnglishName = "French", Code = "fr-CA", Voice = "fr-CA-Caroline", Flag = FlagImageSource("ca.svg") },
                    new Language() { DisplayName = "Français", DisplayCode = "BE",CountryCode = "BE", CountryName = "Belgium", CountryNativeName = "Belgique", Name = "Español (Belgium)", EnglishName = "French", Code = "fr-BE", Voice = "fr-BE-CharlineNeural", Flag = FlagImageSource("be.svg") },
                    new Language() { DisplayName = "Français", DisplayCode = "CH",CountryCode = "CH", CountryName = "Switzerland", CountryNativeName = "Suisse", Name = "Español (Switzerland)", EnglishName = "French", Code = "fr-CH", Voice = "fr-CH-ArianeNeural", Flag = FlagImageSource("ch.svg") },
                    new Language() { DisplayName = "Nederlands", DisplayCode = "BE",CountryCode = "BE", CountryName = "Belgium", CountryNativeName = "België", Name = "Nederlands (Belgium)", EnglishName = "Dutch", Code = "nl-BE", Voice = "nl-BE-ArnaudNeural", Flag = FlagImageSource("be.svg") },
                    new Language() { DisplayName = "Kiswahili", DisplayCode = "KE",CountryCode = "KE", CountryName = "Kenya", CountryNativeName = "Kenya", Name = "Kiswahili (Kenya)", EnglishName = "Swahili", Code = "sw-KE", Voice = "sw-KE-ZuriNeural", Flag = FlagImageSource("ke.svg") },
                    new Language() { DisplayName = "Kiswahili", DisplayCode = "TZ",CountryCode = "TZ", CountryName = "Tanzania", CountryNativeName = "Tanzania", Name = "Kiswahili (Tanzania)", EnglishName = "Swahili", Code = "sw-TZ", Voice = "sw-TZ-DaudiNeural", Flag = FlagImageSource("tz.svg") },
                    new Language() { DisplayName = "தமிழ்", DisplayCode = "IND",CountryCode = "IN", CountryName = "India", CountryNativeName = "இந்தியா", Name = "தமிழ் (India)", EnglishName = "Tamil", Code = "ta-IN", Voice = "ta-IN-Valluvar", Flag = FlagImageSource("in.svg") },
                    new Language() { DisplayName = "தமிழ்", DisplayCode = "LK",CountryCode = "LK", CountryName = "Sri Lanka", CountryNativeName = "இலங்கை", Name = "தமிழ் (Sri Lanka)", EnglishName = "Tamil", Code = "ta-LK", Voice = "ta-LK-KumarNeural", Flag = FlagImageSource("lk.svg") },
                    new Language() { DisplayName = "தமிழ்", DisplayCode = "MY",CountryCode = "MY", CountryName = "Malaysia", CountryNativeName = "மலேசியா", Name = "தமிழ் (Malaysia)", EnglishName = "Tamil", Code = "ta-MY", Voice = "ta-MY-KaniNeural", Flag = FlagImageSource("my.svg") },
                    new Language() { DisplayName = "தமிழ்", DisplayCode = "SG",CountryCode = "SG", CountryName = "Singapore", CountryNativeName = "சிங்கப்பூர்", Name = "தமிழ் (Singapore)", EnglishName = "Tamil", Code = "ta-SG", Voice = "ta-SG-AnbuNeural", Flag = FlagImageSource("sg.svg") },
                    new Language() { DisplayName = "اُردُو", DisplayCode = "UR",CountryCode = "PK", CountryName = "Pakistan", CountryNativeName = "پاکستان", Name = "اُردُو (Pakistan)", EnglishName = "Urdu", Code = "ur-PK", Voice = "ur-PK-AsadNeural", Flag = FlagImageSource("pk.svg") },
                    new Language() { DisplayName = "اُردُو", DisplayCode = "UR",CountryCode = "IN", CountryName = "India", CountryNativeName = "انڈیا", Name = "اُردُو (India)", EnglishName = "Urdu", Code = "ur-IN", Voice = "ur-IN-GulNeural", Flag = FlagImageSource("in.svg") },
                    new Language() { DisplayName = "Català", DisplayCode = "ES",CountryCode = "ES", CountryName = "Spain", CountryNativeName = "España", Name = "Català (Spain)", EnglishName = "Catalan", Code = "ca-ES", Voice = "ca-ES-HerenaRUS", Flag = FlagImageSource("es.svg") },
                    new Language() { DisplayName = "Dansk", DisplayCode = "DEN",CountryCode = "DK", CountryName = "Denmark", CountryNativeName = "Danmark", Name = "Dansk (Denmark)", EnglishName = "Danish", Code = "da-DK", Voice = "da-DK-HelleRUS", Flag = FlagImageSource("dk.svg") },
                    new Language() { DisplayName = "English", DisplayCode = "AUS",CountryCode = "AU", CountryName = "Australia", CountryNativeName = "Australia", Name = "English (Australia)", EnglishName = "English", Code = "en-AU", Voice = "en-AU-Catherine", Flag = FlagImageSource("au.svg") },
                    new Language() { DisplayName = "Suomi", DisplayCode = "FIN",CountryCode = "FI", CountryName = "Finland", CountryNativeName = "Suomi", Name = "Suomi (Finland)", EnglishName = "Finnish", Code = "fi-FI", Voice = "fi-FI-HeidiRUS", Flag = FlagImageSource("fi.svg") },
                    new Language() { DisplayName = "हिन्दी", DisplayCode = "IND",CountryCode = "IN", CountryName = "India", CountryNativeName = "India", Name = "हिन्दी (India)", EnglishName = "Hindi", Code = "hi-IN", Voice = "hi-IN-Kalpana-Apollo", Flag = FlagImageSource("in.svg") },
                    new Language() { DisplayName = "日本語", DisplayCode = "JAP",CountryCode = "JP", CountryName = "Japan", CountryNativeName = "日本", Name = "日本語 (Japan)", EnglishName = "Japanese", Code = "ja-JP", Voice = "ja-JP-Ayumi-Apollo", Flag = FlagImageSource("jp.svg") },
                    new Language() { DisplayName = "조선말", DisplayCode = "KR",CountryCode = "KR", CountryName = "South Korea", CountryNativeName = "한국", Name = "조선말 (Korea)", EnglishName = "Korean", Code = "ko-KR", Voice = "ko-KR-HeamiRUS", Flag = FlagImageSource("kr.svg") },
                    new Language() { DisplayName = "Norsk", DisplayCode = "NOR",CountryCode = "NO", CountryName = "Norway", CountryNativeName = "Norge", Name = "Norsk (Bokmål) (Norway)", EnglishName = "Norwegian", Code = "nb-NO", Voice = "nb-NO-HuldaRUS", Flag = FlagImageSource("no.svg") },
                    new Language() { DisplayName = "Język polski", DisplayCode = "POL",CountryCode = "PL", CountryName = "Poland", CountryNativeName = "Polska", Name = "Język polski (Poland)", EnglishName = "Polish", Code = "pl-PL", Voice = "pl-PL-PaulinaRUS", Flag = FlagImageSource("pl.svg") },
                    new Language() { DisplayName = "Português", DisplayCode = "BR",CountryCode = "BR", CountryName = "Brazil", CountryNativeName = "Brasil", Name = "Português (Brazil)", EnglishName = "Portuguese", Code = "pt-BR", Voice = "pt-BR-HeloisaRUS", Flag = FlagImageSource("br.svg") },
                    new Language() { DisplayName = "Português", DisplayCode = "PT", CountryCode = "PT", CountryName = "Portugal", CountryNativeName = "Portugal", Name = "Português (Portugal)", EnglishName = "Portuguese", Code = "pt-PT", Voice = "pt-PT-HeliaRUS", Flag = FlagImageSource("pt.svg") },
                    new Language() { DisplayName = "Русский", DisplayCode = "RUS",CountryCode = "RU", CountryName = "Russia", CountryNativeName = "Россия", Name = "Русский (Russia)", EnglishName = "Russian", Code = "ru-RU", Voice = "ru-RU-Irina-Apollo", Flag = FlagImageSource("ru.svg") },
                    new Language() { DisplayName = "తెలుగు", DisplayCode = "IND",CountryCode = "IN", CountryName = "India", CountryNativeName = "India", Name = "తెలుగు (India)", EnglishName = "Telugu", Code = "te-IN", Voice = "te-IN-Chitra", Flag = FlagImageSource("in.svg") },
                    new Language() { DisplayName = "國語", DisplayCode = "CN",CountryCode = "CN", CountryName = "China", CountryNativeName = "中国", Name = "國語 (Mandarin, Simplified)", EnglishName = "Chinese", Code = "zh-CN", Voice = "zh-CN-HuihuiRUS", Flag = FlagImageSource("cn.svg") },
                    new Language() { DisplayName = "廣東話", DisplayCode = "HK",CountryCode = "CN", CountryName = "China", CountryNativeName = "中国", Name = "廣東話 (Cantonese, Traditional)", EnglishName = "Chinese", Code = "zh-HK", Voice = "zh-HK-Tracy-Apollo", Flag = FlagImageSource("hk.svg") },
                    new Language() { DisplayName = "福佬話", DisplayCode = "TW",CountryCode = "CN", CountryName = "China", CountryNativeName = "中国", Name = "福佬話 (Taiwanese Mandarin)", EnglishName = "Chinese", Code = "zh-TW", Voice = "zh-TW-Yating-Apollo", Flag = FlagImageSource("tw.svg") },
                    new Language() { DisplayName = "ภาษาไทย", DisplayCode = "TH",CountryCode = "TH", CountryName = "Thailand", CountryNativeName = "ประเทศไทย", Name = "ภาษาไทย (Thailand)", EnglishName = "Thai", Code = "th-TH", Voice = "th-TH-Pattara", Flag = FlagImageSource("th.svg") },
                    new Language() { DisplayName = "Türkçe", DisplayCode = "TUR",CountryCode = "TR", CountryName = "Turkey", CountryNativeName = "Turkiye", Name = "Türkçe (Turkey)", EnglishName = "Turkey", Code = "tr-TR", Voice = "tr-TR-SedaRUS", Flag = FlagImageSource("tr.svg") },
                    new Language() { DisplayName = "български език", DisplayCode = "BG",CountryCode = "BG", CountryName = "Bulgaria", CountryNativeName = "Bŭlgariya", Name = "ългарски език (Bulgaria)", EnglishName = "Bulgarian", Code = "bg-BG", Voice = "bg-BG-Ivan", Flag = FlagImageSource("bg.svg") },
                    new Language() { DisplayName = "Hrvatski", DisplayCode = "CRO",CountryCode = "HR", CountryName = "Croatia", CountryNativeName = "Hrvatska", Name = "Hrvatski (Croatia)", EnglishName = "Croatian", Code = "hr-HR", Voice = "hr-HR-Matej", Flag = FlagImageSource("hr.svg") },
                    new Language() { DisplayName = "Český Jazyk", DisplayCode = "CZ",CountryCode = "CZ", CountryName = "Czech", CountryNativeName = "Česko", Name = "Český Jazyk (Czech)", EnglishName = "Czech", Code = "cs-CZ", Voice = "cs-CZ-Jakub", Flag = FlagImageSource("cz.svg") },
                    new Language() { DisplayName = "Ελληνικά", DisplayCode = "GR",CountryCode = "GR", CountryName = "Greece", CountryNativeName = "Ελλάς", Name = "Ελληνικά (Greece)", EnglishName = "Greek", Code = "el-GR", Voice = "el-GR-Stefanos", Flag = FlagImageSource("gr.svg") },
                    new Language() { DisplayName = "Magyar", DisplayCode = "HUN",CountryCode = "HU", CountryName = "Hungary", CountryNativeName = "Magyarország", Name = "Magyar (Hungary)", EnglishName = "Hungarian", Code = "hu-HU", Voice = "hu-HU-Szabolcs", Flag = FlagImageSource("hu.svg") },
                    new Language() { DisplayName = "Română", DisplayCode = "RO",CountryCode = "RO", CountryName = "Romania", CountryNativeName = "România", Name = "Română (Romania)", EnglishName = "Romanian", Code = "ro-RO", Voice = "ro-RO-Andrei", Flag = FlagImageSource("ro.svg") },
                    new Language() { DisplayName = "Slovenčina", DisplayCode = "SK", CountryCode = "SK", CountryName = "Slovakia", CountryNativeName = "Slovensko", Name = "Slovenčina (Slovakia)", EnglishName = "Slovak", Code = "sk-SK", Voice = "sk-SK-Filip", Flag = FlagImageSource("sk.svg") },
                    new Language() { DisplayName = "Slovenščina", DisplayCode = "SL",CountryCode = "SI", CountryName = "Slovenia", CountryNativeName = "Slovenija", Name = "Slovenščina (Slovenia)", EnglishName = "Slovenian", Code = "sl-SI", Voice = "sl-SI-Lado", Flag = FlagImageSource("si.svg") },
                    new Language() { DisplayName = "עברית", DisplayCode = "IL",CountryCode = "IL", CountryName = "Israel", CountryNativeName = "Yisrael", Name = "עברית (Israel)", EnglishName = "Hebrew", Code = "he-IL", Voice = "he-IL-Asaf", Flag = FlagImageSource("il.svg") },
                    new Language() { DisplayName = "Bahasa Indonesia", DisplayCode = "ID",CountryCode = "ID", CountryName = "Indonesia", CountryNativeName = "Indonesia", Name = "Bahasa Indonesia (Indonesia)", EnglishName = "Indonesian", Code = "id-ID", Voice = "id-ID-Andika", Flag = FlagImageSource("id.svg") },
                    new Language() { DisplayName = "بهاس ملايو", DisplayCode = "MY",CountryCode = "MY", CountryName = "Malaysia", CountryNativeName = "Məlejsiə", Name = "بهاس ملايو (Malaysia)", EnglishName = "Malay", Code = "ms-MY", Voice = "ms-MY-Rizwan", Flag = FlagImageSource("my.svg") },
                    new Language() { DisplayName = "Tiếng Việt Nam", DisplayCode = "VN",CountryCode = "VN", CountryName = "Vietnam", CountryNativeName = "Việt Nam", Name = "Tiếng Việt Nam (Vietnam)", EnglishName = "Vietnamese", Code = "vi-VN", Voice = "vi-VN-An", Flag = FlagImageSource("vn.svg") },
                    new Language() { DisplayName = "Eesti", DisplayCode = "EE",CountryCode = "EE", CountryName = "Estonia", CountryNativeName = "Eesti", Name = "Eesti (Estonia)", EnglishName = "Estonian", Code = "et-EE", Voice = "et-EE-AnuNeural", Flag = FlagImageSource("ee.svg") },
                    new Language() { DisplayName = "ગુજરાતી", DisplayCode = "IN",CountryCode = "IN", CountryName = "India", CountryNativeName = "India", Name = "ગુજરાતી (India)", EnglishName = "Gujarati", Code = "gu-IN", Voice = "gu-IN-DhwaniNeural", Flag = FlagImageSource("in.svg") },
                    new Language() { DisplayName = "latviešu", DisplayCode = "LV",CountryCode = "LV", CountryName = "Latvia", CountryNativeName = "Latvija", Name = "latviešu (Latvia)", EnglishName = "Latvian", Code = "lv-LV", Voice = "lv-LV-EveritaNeural", Flag = FlagImageSource("lv.svg") },
                    new Language() { DisplayName = "Lietuvių", DisplayCode = "LT",CountryCode = "LT", CountryName = "Lithuania", CountryNativeName = "Lietuva", Name = "Lietuvių (Lithuania)", EnglishName = "Lithuanian", Code = "lt-LT", Voice = "lt-LT-OnaNeural", Flag = FlagImageSource("lt.svg") },
                    new Language() { DisplayName = "Malti", DisplayCode = "MT",CountryCode = "MT", CountryName = "Malta", CountryNativeName = "Malta", Name = "Malti (Malta)", EnglishName = "Maltese", Code = "mt-MT", Voice = "mt-MT-GraceNeural", Flag = FlagImageSource("mt.svg") },
                    new Language() { DisplayName = "मराठी", DisplayCode = "IN",CountryCode = "IN", CountryName = "India", CountryNativeName = "India", Name = "मराठी (India)", EnglishName = "Marathi", Code = "mr-IN", Voice = "mr-IN-AarohiNeural", Flag = FlagImageSource("in.svg") },
                    new Language() { DisplayName = "Gaeilge", DisplayCode = "IE",CountryCode = "IE", CountryName = "Ireland", CountryNativeName = "Éire", Name = "Gaeilge (Ireland)", EnglishName = "Gaelic", Code = "ga-IE", Voice = "ga-IE-OrlaNeural", Flag = FlagImageSource("ie.svg") },
                    new Language() { DisplayName = "украї́нська мо́ва", DisplayCode = "UA",CountryCode = "UA", CountryName = "Ukraine", CountryNativeName = "Ukraїna", Name = "украї́нська мо́ва (Ukraine)", EnglishName = "Ukrainian", Code = "uk-UA", Voice = "uk-UA-PolinaNeural", Flag = FlagImageSource("ua.svg") },
                    new Language() { DisplayName = "Wikang Filipino", DisplayCode = "PH",CountryCode = "PH", CountryName = "Philippines", CountryNativeName = "Wikang Filipino", Name = "Wikang Filipino (Philippines)", EnglishName = "Filipino", Code = "fil-PH", Voice = "fil-PH-BlessicaNeural", Flag = FlagImageSource("ph.svg") },
                    //new Language() { DisplayName = "বাংলা", DisplayCode = "BD",CountryCode = "BD", CountryName = "Bangladesh", CountryNativeName = "বাংলা", Name = "বাংলা (Bangladesh)", EnglishName = "Bangla", Code = "bn-BD", Voice = "bn-BD-NabanitaNeural", Flag = FlagImageSource("bd.svg") },
                    new Language() { DisplayName = "नेपाली", DisplayCode = "NP",CountryCode = "NP", CountryName = "Nepal", CountryNativeName = "नेपाली", Name = "नेपाली (Nepal)", EnglishName = "Nepali", Code = "ne-NP", Voice = "ne-NP-HemkalaNeural", Flag = FlagImageSource("np.svg") },
                    //new Language() { DisplayName = "српски", DisplayCode = "RS",CountryCode = "RS", CountryName = "Serbia", CountryNativeName = "српски", Name = "српски (Serbia)", EnglishName = "Serbian", Code = "sr-RS", Voice = "sr-RS-SophieNeural", Flag = FlagImageSource("rs.svg") },
                    new Language() { DisplayName = "Cymraeg", DisplayCode = "WLS",CountryCode = "WLS", CountryName = "Wales", CountryNativeName = "Cymraeg", Name = "Cymraeg (Wales)", EnglishName = "Welsh", Code = "cy-GB", Voice = "cy-GB-NiaNeural", Flag = FlagImageSource("gb-wls.svg") },
                    new Language() { DisplayName = "босански", DisplayCode = "BA",CountryCode = "BA", CountryName = "Bosnia", CountryNativeName = "босански", Name = "босански (Bosnia)", EnglishName = "Bosnian", Code = "bs-BA", Voice = "bs-BA-VesnaNeural", Flag = FlagImageSource("ba.svg") },
                    new Language() { DisplayName = "Afrikaans", DisplayCode = "AF",CountryCode = "ZA", CountryName = "South Africa", CountryNativeName = "Suid-Afrika", Name = "Afrikaans (South Africa)", EnglishName = "Afrikaans", Code = "af-ZA", Voice = "af-ZA-AdriNeural", Flag = FlagImageSource("za.svg") },
                    new Language() { DisplayName = "Shqip", DisplayCode = "SQ",CountryCode = "AL", CountryName = "Albania", CountryNativeName = "Shqipërisë", Name = "Albanian (Albania)", EnglishName = "Albanian", Code = "sq-AL", Voice = "sq-AL-AnilaNeural", Flag = FlagImageSource("al.svg") },
                    new Language() { DisplayName = "āmariññā", DisplayCode = "AM",CountryCode = "ET", CountryName = "Ethiopia", CountryNativeName = "ʾĪtyōṗṗyā", Name = "Amharic (Ethiopia)", EnglishName = "Amharic", Code = "am-ET", Voice = "am-ET-AmehaNeural", Flag = FlagImageSource("et.svg") },
                    new Language() { DisplayName = "hayeren", DisplayCode = "HY",CountryCode = "AM", CountryName = "Armenia", CountryNativeName = "Hayk", Name = "Armenian (Armenia)", EnglishName = "Armenian", Code = "hy-AM", Voice = "hy-AM-AnahitNeural", Flag = FlagImageSource("am.svg") },
                    new Language() { DisplayName = "Íslenska", DisplayCode = "IS",CountryCode = "IS", CountryName = "Iceland", CountryNativeName = "Ísland", Name = "Icelandic (Iceland)", EnglishName = "Icelandic", Code = "is-IS", Voice = "is-IS-GudrunNeural", Flag = FlagImageSource("is.svg") },
                    new Language() { DisplayName = "ಕನ್ನಡ", DisplayCode = "KN",CountryCode = "IN", CountryName = "India", CountryNativeName = "ಭಾರತ", Name = "Kannada (India)", EnglishName = "Kannada", Code = "kn-IN", Voice = "kn-IN-GaganNeural", Flag = FlagImageSource("in.svg") },
                    new Language() { DisplayName = "Қазақ Tілі", DisplayCode = "KK",CountryCode = "KZ", CountryName = "Kazakhstan", CountryNativeName = "Қазақстан", Name = "Kazakh (Kazakhstan)", EnglishName = "Kazakh", Code = "kk-KZ", Voice = "kk-KZ-AigulNeural", Flag = FlagImageSource("kz.svg") },
                    new Language() { DisplayName = "ភាសាខ្មែរ", DisplayCode = "KM",CountryCode = "KH", CountryName = "Cambodia", CountryNativeName = "កម្ពុជា។", Name = "Khmer (Cambodia)", EnglishName = "Khmer", Code = "km-KH", Voice = "km-KH-PisethNeural", Flag = FlagImageSource("kh.svg") },
                    new Language() { DisplayName = "ພາສາລາວ", DisplayCode = "LO",CountryCode = "LA", CountryName = "Laos", CountryNativeName = "ປະເທດລາວ", Name = "Lao (Laos)", EnglishName = "Lao", Code = "lo-LA", Voice = "lo-LA-ChanthavongNeural", Flag = FlagImageSource("la.svg") },
                    new Language() { DisplayName = "മലയാളം", DisplayCode = "ML",CountryCode = "IN", CountryName = "India", CountryNativeName = "ഇന്ത്യ", Name = "Malayalam (India)", EnglishName = "Malayalam", Code = "ml-IN", Voice = "ml-IN-MidhunNeural", Flag = FlagImageSource("in.svg") },
                    new Language() { DisplayName = "မြန်မာ", DisplayCode = "MY",CountryCode = "MM", CountryName = "Myanmar", CountryNativeName = "မြန်မာ", Name = "Burmese (Myanmar)", EnglishName = "Burmese", Code = "my-MM", Voice = "my-MM-NilarNeural", Flag = FlagImageSource("mm.svg") },
                    new Language() { DisplayName = "پښتو", DisplayCode = "PS",CountryCode = "AF", CountryName = "Afghanistan", CountryNativeName = "افغانستان", Name = "Pashto (Afghanistan)", EnglishName = "Pashto", Code = "ps-AF", Voice = "ps-AF-GulNawazNeural", Flag = FlagImageSource("af.svg") },
                    new Language() { DisplayName = "فارسی", DisplayCode = "FA",CountryCode = "IR", CountryName = "Iran", CountryNativeName = "ایران", Name = "Persian (Iran)", EnglishName = "Persian", Code = "fa-IR", Voice = "fa-IR-DilaraNeural", Flag = FlagImageSource("ir.svg") },

                };
            approvedlanguages = new List<Language>(languages);
            var currentList = await _dataService.GetBackendLanguagesAsync();

            if (currentList == null || currentList.Count == 0)
            {
                return languages;
            }

            foreach (var code in currentList)
            {
                var foundLanguage = languages.FirstOrDefault(c => c.Code.ToLower() == code.ToLower());
                if (foundLanguage != null && !approvedlanguages.Exists(c => c.Code.ToLower() == code.ToLower()))
                {
                    approvedlanguages.Add(foundLanguage);
                }
            }

            return approvedlanguages;
        }

        private SvgImageSource FlagImageSource(string name)
        {
            return new SvgImageSource(new Uri($"ms-appx:///Assets/Flags/{name}"));
        }
    }
}
